AllCops:
  Exclude:
    - "README.md"
    - "Guardfile"
    - "Rakefile"
    - "./lib/tic_tac_toe.rb"

  DisplayCopNames: true

Layout/LineLength:
  Max: 120
  Enabled: true
Metrics/MethodLength:
  Max: 20
  Enabled: true
Metrics/AbcSize:
  Max: 50
  Enabled: true
Metrics/ClassLength:
  Max: 150
  Enabled: true
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30
  Enabled: true


Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
